apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter
  namespace: prometheus
data:
  config.yaml: |
    rules:
    - seriesQuery: 'http_requests_total{namespace="moc", service="moc"}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          service: {resource: "service"}
      name:
        matches: "^(.*)_total$"
        as: "${1}_per_second" # Transforma 'http_requests_total' em 'http_requests_per_second'
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (pod)