apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: moc-high-tps
  namespace: moc
spec:
  scaleTargetRef:
    name: moc
  minReplicaCount: 1
  maxReplicaCount: 30
  pollingInterval: 10  
  cooldownPeriod:  30
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
        scaleUp:
          stabilizationWindowSeconds: 30          
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
      metricName: istio_requests_total 
      threshold: "5" # <---- Quantidade de requisições por pod. No exemplo, 5 TPS. 
      query: |
        sum(rate(istio_requests_total{destination_service_name="moc"}[1m])) 