apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: moc
spec:
  podIdentity:
    provider: aws
    roleArn: arn:aws:iam::707257249187:role/webinar-infnet-keda
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: moc-high-tps
  namespace: moc
spec:
  
  scaleTargetRef:
    name: consumer
    
  minReplicaCount: 0
  maxReplicaCount: 30
  pollingInterval: 10  
  cooldownPeriod:  30
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
        scaleUp:
          stabilizationWindowSeconds: 30          
  triggers:
 # - type: prometheus
 #   metadata:
 #     serverAddress: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
 #     metricName: istio_requests_total 
 #     threshold: "5" # <---- Quantidade de requisições por pod. No exemplo, 5 TPS. 
 #     query: |
 #       sum(rate(istio_requests_total{destination_service_name="moc"}[1m])) 

  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      awsRegion: us-east-1
      queueURL: https://sqs.us-east-1.amazonaws.com/707257249187/teste
      queueLength: "20" # <---- Quantidade de mensagens na fila. No exemplo, 5 mensagens. 
      identityOwner: operator

      
      