apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: moc-sm
  namespace: moc
  
spec:
  selector:
    matchLabels:
      # Este seletor deve corresponder ao label do seu Service
      app: moc
  endpoints:
  - port: http # Deve corresponder ao nome da porta no Service
    #path: /metrics # A rota onde as métricas são expostas
    interval: 10s # Frequência de coleta