apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: moc-hpa-requests
  namespace: moc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: moc
  minReplicas: 1
  maxReplicas: 30
  metrics:
  - type: Pods
    pods: # O bloco 'pods' contém tanto 'metric' quanto 'target'
      metric:
        name: http_requests_per_second
      target: # <- Corretamente indentado DENTRO de 'pods'
        type: AverageValue
        # O valor "3k" (3000) veio da sua mensagem de erro.
        # O HPA tentará manter a média de 3000 requisições/segundo por pod.
        averageValue: "3"

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 20
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 20
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30