# HPA para escalonamento automático da aplicação MOC baseado em CPU
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: moc-hpa
  namespace: moc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: moc  # Deployment alvo do autoscaling
  minReplicas: 1    # Mínimo de 1 pod
  maxReplicas: 5    # Máximo de 5 pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # Target de 60% de CPU
   
  behavior:
    scaleUp:  # Comportamento para escalar para cima
      stabilizationWindowSeconds: 20
      policies:
      - type: Pods
        value: 3          # Adiciona 1 pod por vez
        periodSeconds: 30 # A cada 30 segundos
    scaleDown:  # Comportamento para escalar para baixo
      stabilizationWindowSeconds: 20
      policies:
      - type: Pods
        value: 1          # Remove 1 pod por vez
        periodSeconds: 30 # A cada 30 segundos