apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: moc-hpa
  namespace: moc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: moc
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
   
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 20
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 20
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30