{
 "title": "webinar",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU_usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"moc\",container=\"moc\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "#NÓS",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (label_node_kubernetes_io_instance_type) (kube_node_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "#PODS",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"moc\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests_per_second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}